spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://127.0.0.1:5432/accumulate_coding?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&stringtype=unspecified
    username: postgres
    password: hyc123
    driverClassName: org.postgresql.Driver
    initialSize: 5
    minIdle: 1
    maxActive: 25
    maxWait: 60000
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
  security:
    basic:
      enabled: true
      path: /swagger-ui.html
    user:
      name: shuidi
      password: 3body
  #访问方式：localhost:8090/swagger-ui.html
  swagger:
    base-path: /**
    base-package: 'com.accumulate'
    title: 'spring-boot-swagger-tool'
    description: '基于Swagger构建的SpringBoot RESTApi 文档'
    version: '1.0'
    serviceUrl: 'http://shuidi.tool.com'
    contact:
      name: '水滴'
      url: 'http://shuidi.com'
      email: 'shuidi.com'
mybatis-plus:
  typeEnumsPackage: com.accumulate.coding.tool.enums
  configuration:
    cache-enabled: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate.ddl-auto: create
    open-in-view: false
    hibernate:
      ddl-auto: none
      hibernate:
        hbm2ddl.auto: none
        enable_lazy_load_no_trans: true
      show-sql: true
accumulate:
  coding:
    tool:
      log:
        path: ../log
        level: INFO
server:
  servlet:
    context-path: /
  port: 8090