spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://127.0.0.1:5432/accumulate-coding?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&stringtype=unspecified
    username: root
    password: hyc123
    driverClassName: org.postgresql.Driver
    initialSize: 5
    minIdle: 1
    maxActive: 25
    maxWait: 60000
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
mybatis-plus:
  global-config:
    db-config:
      db-type: postgresql
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate.ddl-auto: create
    open-in-view: false
    hibernate:
      ddl-auto: none
      hibernate:
        hbm2ddl.auto: none
        enable_lazy_load_no_trans: true
      show-sql: true
  redis:
    open: true
    leaseTime: 30
    database: 10
    timeout: 3000
    host: 127.0.0.1
    port: 6379
    password: workorder
    lettuce:
      pool:
        max-total: 500
        max-idle: 20
        min-idle: 8
        max-wait: 1000

accumulate:
  coding:
    tool:
      log:
        path: ../log
        level: INFO
server:
  servlet:
    context-path: /