spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/accumulate_coding?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: hyc123
    driverClassName: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 1
    maxActive: 25
    maxWait: 60000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate.ddl-auto: create
    open-in-view: false
    hibernate:
      ddl-auto: none
      hibernate:
        hbm2ddl.auto: none
        enable_lazy_load_no_trans: true
      show-sql: true
  redis:
    open: true
    leaseTime: 30
    database: 10
    timeout: 3000
    host: 127.0.0.1
    port: 6379
    password: workorder
    lettuce:
      pool:
        max-total: 500
        max-idle: 20
        min-idle: 8
        max-wait: 1000

accumulate:
  coding:
    tool:
      log:
        path: ../log
        level: INFO
server:
  servlet:
    context-path: /