spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://127.0.0.1:5432/accumulate_coding?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&stringtype=unspecified
    username: postgres
    password: hyc123
    driverClassName: org.postgresql.Driver
    initialSize: 5
    minIdle: 1
    maxActive: 25
    maxWait: 60000
  redis:
    open: true
    leaseTime: 30
    database: 10
    timeout: 3000
    host: 127.0.0.1
    port: 6379
    password: workorder
    lettuce:
      pool:
        max-total: 500
        max-idle: 20
        min-idle: 8
        max-wait: 1000
  #访问方式：localhost:8090/swagger-ui.html
  swagger:
    base-path: /**
    base-package: 'com.accumulate'
    title: 'spring-boot-swagger-tool'
    description: '基于Swagger构建的SpringBoot RESTApi 文档'
    version: '1.0'
    serviceUrl: 'http://shuidi.tool.com'
    contact:
      name: '水滴'
      url: 'http://shuidi.com'
      email: 'shuidi.com'

accumulate:
  coding:
    web:
      log:
        path: ../log
        level: INFO
server:
  servlet:
    context-path: /
  port: 8090

