spring:
  thymeleaf:
    prefix: classpath:/static/
<<<<<<< HEAD
=======
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/accumulate_coding?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&stringtype=unspecified
    username: postgres
    password: hyc123
    driverClassName: org.postgresql.Driver
    initialSize: 5
    minIdle: 1
    maxActive: 25
    maxWait: 60000
    hikari:
      maximum-pool-size: 10
      connection-timeout: 60000
      minimum-idle: 1
accumulate:
  coding:
    security:
      log:
        level: INFO
        path: ../../../logs
>>>>>>> f16d660b71ef2aab21df2a8de9f93fda3c3478e3
